apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-cluster-registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: in-cluster-registry
  template:
    metadata:
      labels:
        app: in-cluster-registry
    spec:
      containers:
      - image: registry:2
        imagePullPolicy: IfNotPresent
        name: in-cluster-registry
        resources: {}
        volumeMounts:
          - name: registry-volume
            mountPath: /var/lib/registry
      volumes:
        - name: registry-volume
          persistentVolumeClaim:
            claimName: registry-data
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-data
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path

---

apiVersion: v1
kind: Service
metadata:
  name: in-cluster-registry-service
  namespace: registry
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: in-cluster-registry
  type: ClusterIP
