apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: site-builder
  namespace: efb
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["helm.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-site
  namespace: efb
subjects:
  - kind: ServiceAccount
    name: efb-erpnext
    namespace: efb
roleRef:
  kind: Role
  name: site-builder
  apiGroup: rbac.authorization.k8s.io
