name: Build Container Images

on:
  push:
    branches: [ main ]
    tags:
      - "*.*.*"

jobs:
  build_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            registry.castlecraft.co.in/efb-worker
          # add git short SHA as Docker tag
          tag-semver: |
            {{raw}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.castlecraft.co.in
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          repository: registry.castlecraft.co.in/efb-worker
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: containers/worker/Dockerfile
  build_nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            registry.castlecraft.co.in/efb-nginx
          # add git short SHA as Docker tag
          tag-semver: |
            {{raw}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.castlecraft.co.in
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          repository: registry.castlecraft.co.in/efb-nginx
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: containers/nginx/Dockerfile
